In [21]:
import torch
from torch import nn

kpts = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]], dtype=torch.float32)
one = kpts.new_tensor(1)
ones = kpts.new_tensor([1,3])
size0 = torch.stack([one*50,one*100],dim=0)
size1 = torch.stack([ones*50,ones*100],dim = 0)
size2 = torch.stack([one*50,one*100],dim = 0)
size3 = torch.stack([ones*50,ones*100], dim=1)
print(size0)
print(size1)
print(size2)
print(size3)

print(kpts)
a = torch.stack([kpts,kpts],dim = 0)
b = torch.stack([kpts,kpts],dim = 1)
c = torch.stack([kpts,kpts],dim = 2)
d = torch.stack([kpts,kpts],dim = 3)
print(a)
print(b)
print(c)    
print(d)


tensor([ 50., 100.])
tensor([[ 50., 150.],
        [100., 300.]])
tensor([ 50., 100.])
tensor([[ 50., 100.],
        [150., 300.]])
tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
tensor([[[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.],
          [ 7.,  8.,  9.]],

         [[10., 11., 12.],
          [13., 14., 15.],
          [16., 17., 18.]]],


        [[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.],
          [ 7.,  8.,  9.]],

         [[10., 11., 12.],
          [13., 14., 15.],
          [16., 17., 18.]]]])
tensor([[[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.],
          [ 7.,  8.,  9.]],

         [[ 1.,  2.,  3.],
          [ 4.,  5.,  6.],
          [ 7.,  8.,  9.]]],


        [[[10., 11., 12.],
          [13., 14., 15.],
          [16., 17., 18.]],

         [[10., 11., 12.],
          [13., 14., 15.],
          [16., 17., 18.]]]])
tensor([[[[ 1.,  2.,  3.],
          [

0维张量（标量） -> 1维张量 ....  
torch.stack(A,B,dim)，选择在那个维度堆叠A、B  
***注***：维度的索引是从0开始的，即第一个维度对应 dim=0，第二个维度对应 dim=1，以此类推。这里kpts虽然只有三个维度，但stack()中的dim是可以取到dim=3的

In [25]:
import torch
a = torch.randn(1,3,4)
b= a[None,:,:,:]
bb = a[0][1:3]
bbb = a[0,1:3]
e = a.unsqueeze(0)
f = a.unsqueeze(1)
print(a)
print(b)
print(bb)
print(bbb)
x = torch.randn(1,3,1,4)
print(x.shape)
y = x.squeeze()
print(y.shape)
z = x.squeeze(0)
print(z.shape)
q = x.squeeze(1)
print(q.shape)
p = x.squeeze(2)
print(p.shape)
r = x.squeeze(3)
print(r.shape)
t = x.squeeze(-1)
print(t.shape)
u = x.squeeze(-2)
print(u.shape)



tensor([[[-0.5811,  0.9906, -0.4048, -0.8696],
         [-1.4755, -0.9574,  1.5655, -2.3737],
         [-0.9904, -1.5853,  0.3346, -1.2450]]])
tensor([[[[-0.5811,  0.9906, -0.4048, -0.8696],
          [-1.4755, -0.9574,  1.5655, -2.3737],
          [-0.9904, -1.5853,  0.3346, -1.2450]]]])
tensor([[-1.4755, -0.9574,  1.5655, -2.3737],
        [-0.9904, -1.5853,  0.3346, -1.2450]])
tensor([[-1.4755, -0.9574,  1.5655, -2.3737],
        [-0.9904, -1.5853,  0.3346, -1.2450]])
torch.Size([1, 3, 1, 4])
torch.Size([3, 4])
torch.Size([3, 1, 4])
torch.Size([1, 3, 1, 4])
torch.Size([1, 3, 4])
torch.Size([1, 3, 1, 4])
torch.Size([1, 3, 1, 4])
torch.Size([1, 3, 4])


**逐步索引**：a[][]...  
**高级索引**：a[x,y,z,...]  
a[None]相当于a[None,:,:,...] 使用索引的方法简便表示维度的增加位置。

In [29]:
import torch
one1 = torch.tensor([1])
one2 = torch.tensor(1)
print(one1[0]==1)
print(one2==1)

tensor(True)
tensor(True)


tensor([1]) -> 一维的张量 需要索引  
tensor(1) -> 0维的标量 不需要索引

In [100]:
import torch
size = torch.randn(2,3,4)
values, indices = size.max(dim=2)
print(size)
print(values)  # shape: (2, 1)
print(indices)  # shape: (2, 1)


tensor([[[-0.1477,  0.3213, -0.0311,  0.6991],
         [-0.2576, -3.2397, -0.9008,  1.6645],
         [-1.4943, -2.3743,  0.5151, -1.3185]],

        [[-1.2710,  0.5335, -0.8100, -0.4172],
         [-0.0791, -0.2135, -0.1326,  0.1710],
         [ 0.6579, -0.7748,  1.0798, -0.4846]]])
tensor([[0.6991, 1.6645, 0.5151],
        [0.5335, 0.1710, 1.0798]])
tensor([[3, 3, 2],
        [1, 3, 2]])


.max()返回某一维度的最大值与相应索引

In [6]:
import torch

# 创建一个形状为 (2, 3, 4, 5) 的随机张量
scores = torch.arange(1,121).view(2, 3, 4, 5).float()
print(scores)
# 执行 permute 和 reshape 操作
scores = scores.permute(0, 2, 3, 1)
print(scores)
print(scores.shape)

tensor([[[[  1.,   2.,   3.,   4.,   5.],
          [  6.,   7.,   8.,   9.,  10.],
          [ 11.,  12.,  13.,  14.,  15.],
          [ 16.,  17.,  18.,  19.,  20.]],

         [[ 21.,  22.,  23.,  24.,  25.],
          [ 26.,  27.,  28.,  29.,  30.],
          [ 31.,  32.,  33.,  34.,  35.],
          [ 36.,  37.,  38.,  39.,  40.]],

         [[ 41.,  42.,  43.,  44.,  45.],
          [ 46.,  47.,  48.,  49.,  50.],
          [ 51.,  52.,  53.,  54.,  55.],
          [ 56.,  57.,  58.,  59.,  60.]]],


        [[[ 61.,  62.,  63.,  64.,  65.],
          [ 66.,  67.,  68.,  69.,  70.],
          [ 71.,  72.,  73.,  74.,  75.],
          [ 76.,  77.,  78.,  79.,  80.]],

         [[ 81.,  82.,  83.,  84.,  85.],
          [ 86.,  87.,  88.,  89.,  90.],
          [ 91.,  92.,  93.,  94.,  95.],
          [ 96.,  97.,  98.,  99., 100.]],

         [[101., 102., 103., 104., 105.],
          [106., 107., 108., 109., 110.],
          [111., 112., 113., 114., 115.],
          [116., 117.,

这里的轴（维度）交换，并不改变内存位置，实际上是步长（stride）的交换。

In [ ]:
import torch
scores = torch.arange(1,121).view(2, 3, 4, 5).float()
supp_mask = torch.randint(0, 2, scores.shape, dtype=torch.bool)

result = torch.where(supp_mask, torch.zeros_like(scores), scores)

print("supp_mask:\n", supp_mask)
print("result:\n", result)

supp_mask:
 tensor([[[[ True, False, False],
          [ True,  True,  True],
          [ True,  True, False],
          [ True, False,  True],
          [ True, False,  True]],

         [[False,  True,  True],
          [False,  True, False],
          [ True,  True,  True],
          [False, False,  True],
          [ True, False, False]],

         [[ True, False,  True],
          [ True,  True, False],
          [ True,  True, False],
          [False,  True,  True],
          [ True,  True,  True]],

         [[False, False, False],
          [ True,  True,  True],
          [False, False, False],
          [False,  True, False],
          [ True,  True, False]]],


        [[[False, False,  True],
          [False, False,  True],
          [False,  True, False],
          [ True,  True,  True],
          [ True,  True,  True]],

         [[ True, False, False],
          [ True, False, False],
          [ True,  True,  True],
          [ True, False,  True],
          [False,  

类似于三目运算符

In [ ]:
import torch
a = torch.arange(1,101).view(10,10)
k = torch.tensor([
    [1,2],
    [3,4],
    [5,6]
    ])
k_transpose = k.T
b = a[k.T]
c = a[tuple(k.T)]
print(b)
print(c)



tensor([[[11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
         [31., 32., 33., 34., 35., 36., 37., 38., 39., 40.],
         [51., 52., 53., 54., 55., 56., 57., 58., 59., 60.]],

        [[21., 22., 23., 24., 25., 26., 27., 28., 29., 30.],
         [41., 42., 43., 44., 45., 46., 47., 48., 49., 50.],
         [61., 62., 63., 64., 65., 66., 67., 68., 69., 70.]]])
tensor([13., 35., 57.])


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_19268\111152614.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  a = torch.range(1,100).view(10,10)


In [ ]:
import torch
a = torch.arange(0,100).view(10,10)
o0 = a[[[[1,7],[3,4]],[[1,5],[2,8]]]]
o1 = a[[[1,7],[3,4]],:]
o2 = a[([1,7],[3,4])]
o3 = a[[[[1,5]]]]
o4 = a[[1,7],[1,7]]
print("o0:",o0.shape)
print("o1:",o1.shape)
print("o2:",o2.shape)
print("o3:",o3.shape)
print("o4:",o4.shape)
print(o0)
print(o1)
print(o2)
print(o3)
print(o4) 
s = torch.arange(100).reshape(10, 10)
k = torch.tensor([[2, 3], [4, 5], [6, 7]])

# 正确用法
idx = tuple(k.t())  # (tensor([2,4,6]), tensor([3,5,7]))
print(s[idx])  # 输出 tensor([23, 45, 67])

# 错误用法
print(s[[[2,4,6],[3,5,7]]])  # 会报错或结果不是你想要的

o0: torch.Size([2, 2])
o1: torch.Size([2, 2, 10])
o2: torch.Size([2])
o3: torch.Size([1, 2, 10])
o4: torch.Size([2])
tensor([[11, 75],
        [32, 48]])
tensor([[[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
         [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]],

        [[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
         [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]])
tensor([13, 74])
tensor([[[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
         [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]]])
tensor([11, 77])


注意要把tensor转换为元组或列表的形式才可以将其识别为批量索引,否则这个tensor会被整个当作第一个维度的索引，而不会对其拆分。列表或元组都会对其内部拆分，然后内部元素分别对应指定的维度的索引，元素为标量则是单个索引，是多维的则是批量索引

In [95]:
import torch

mat1 = torch.tensor([[1, 5, 3], [4, 2, 6]])
values1, idx1 = torch.topk(mat1, k=2, dim=0)
print(values1)
print(idx1)

import torch

# 创建一个 3D 张量 (shape: 2x3x4)
mat2 = torch.tensor([
    [
        [10, 20, 30, 40],
        [50, 60, 70, 80],
        [90, 100, 110, 120]
    ],
    [
        [15, 25, 35, 45],
        [55, 65, 75, 85],
        [95, 105, 115, 125]
    ]
])

# 沿着 dim=1（即第1维度，行方向）取 top-2
values2, idx2 = torch.topk(mat2, k=2, dim=1)

print("Values2:\n", values2)
print("\nIndices2:\n", idx2)

tensor([[4, 5, 6],
        [1, 2, 3]])
tensor([[1, 0, 1],
        [0, 1, 0]])
Values2:
 tensor([[[ 90, 100, 110, 120],
         [ 50,  60,  70,  80]],

        [[ 95, 105, 115, 125],
         [ 55,  65,  75,  85]]])

Indices2:
 tensor([[[2, 2, 2, 2],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [1, 1, 1, 1]]])


torch.topk(mat，k，dim)在指定维度上求前k个  
**例**：mat.shape 为 (5,6,7)  values, idx = torch.topk(mat,2, 1)  则values 和 idx 的shape 为 (5,***3***,7),values[a][ ***1*** ] [b]索引的结果为在mat[a][:][b]中第 ***1*** 大的数

In [97]:
import torch

a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

b = torch.flip(a, dims=[0])
print(b)
# tensor([[4, 5, 6],
#         [1, 2, 3]])  # 沿着行（dim=0）翻转
c = torch.flip(a, dims=[0, 1])
print(c)
# tensor([[6, 5, 4],
#         [3, 2, 1]])  # 先翻行，再翻列


tensor([[4, 5, 6],
        [1, 2, 3]])
tensor([[6, 5, 4],
        [3, 2, 1]])


In [103]:
import torch

# 输入张量
input_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# 索引张量
index_tensor = torch.tensor([[0, 1, 1], [1, 0, 0]])

# 使用 gather 提取数据
result = input_tensor.gather(0, index_tensor)

print(result)


tensor([[1, 5, 6],
        [4, 2, 3]])


In [5]:
import torch
a = torch.randn(4,7,9)
print(a.shape[:-1])
shape0 = a.shape[:-1]
b = a.new_full(shape0,-1)
print(b)
c = a.new_zeros(shape0)
print(c)

torch.Size([4, 7])
tensor([[-1., -1., -1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1., -1., -1.]])
tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]])
